name: Compatibility Tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
        jest:
          - ./compatibility/24
          - ./compatibility/25
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Link jest-runner-groups
      run: npm link
      env:
        CI: true
    - name: install dependencies
      run: npm ci
      working-directory: ${{ matrix.jest }}
      env:
        CI: true
    - name: add jest-runner-groups
      run: npm link jest-runner-groups
      working-directory: ${{ matrix.jest }}
    - name: run tests
      run: npm test
      working-directory: ${{ matrix.jest }}
