name: Compatibility Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Link jest-runner-groups
      run: npm link
      env:
        CI: true
    - name: go to the compatibility test folder
      run: cd ./compatibility/24
    - name: install dependencies
      run: npm ci
      env:
        CI: true
    - name: add jest-runner-groups
      run: npm link jest-runner-groups
    - name: run tests
      run: npm test
