name: Tests

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
          - 12.x
          - 14.x
        jest:
          - ./jest/24
          - ./jest/25
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install test dependencies
      run: npm ci
      working-directory: ${{ matrix.jest }}
      env:
        CI: true
    - name: add jest-runner-groups@next
      run: npm i jest-runner-groups@next
      working-directory: ${{ matrix.jest }}
    - name: run tests
      run: npm test
      working-directory: ${{ matrix.jest }}
